<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\IdemPotent.Core\IdemPotent.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="StackExchange.Redis" Version="3.0.17" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageId>IdemPotent.Redis</PackageId>
    <Description>Redis-backed idempotency store for IdemPotent ASP.NET Core middleware.</Description>
    <PackageTags>idempotency;aspnetcore;redis;cache;api</PackageTags>
  </PropertyGroup>

</Project>
